action_id: trunk-upgrade-available
date: 2024-02-13 12:51:44
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1707828704
full_timestamp:
  nanos: 152596000
  seconds: 1707828704
trunk_version: 1.19.0
