action_id: trunk-upgrade-available
date: 2024-02-14 08:53:48
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1707900828
full_timestamp:
  nanos: 645047000
  seconds: 1707900828
trunk_version: 1.19.0
