action_id: trunk-share-with-everyone
date: 2024-02-13 05:44:22
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1707803062
full_timestamp:
  nanos: 522139000
  seconds: 1707803062
trunk_version: 1.19.0
